## Numpy

In [1]:
import numpy as np

In [3]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [4]:
type(a)

numpy.ndarray

In [5]:
type(a[0])

numpy.float64

In [7]:
a = np.zeros(3, dtype=int)
type(a[0])

numpy.int32

In [8]:
z = np.zeros(10)

In [9]:
z.shape

(10,)

In [13]:
z.shape = (10, 1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [15]:
z = np.zeros(4)
z.shape = (2, 2)
z

array([[0., 0.],
       [0., 0.]])

In [19]:
z1 = np.empty(3)
print(z1)
z2 = np.zeros(3)
print(z2)
print(id(z1))
print(id(z2))

[0. 0. 0.]
[0. 0. 0.]
2896381250096
2896381250576


In [21]:
z = np.linspace(2, 4, 5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [22]:
z = np.identity(6666)
z

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [38]:
z3 = np.array([10, 20])
z4 = np.array((10,20))
id(z3) == id(z4)

False

In [44]:
z5 = np.array((10,20), dtype=float)
print(id(z5[0]))
z6 = np.array([10,20], dtype=float)
print(id(z6[0]))

2896380677392
2896380677648


In [50]:
z1 = np.array([[1, 2], [3, 4]])
z2 = np.array([(1, 2), (3, 4)])
z3 = np.array(([1, 2], [3, 4]))
print(id(z1),id(z2),id(z3))

2896381543168 2896381529104 2896381250096


In [59]:
na = np.linspace(10, 20, 2)
na is np.asarray(na)

True

In [58]:
na is np.array(na)

False

In [61]:
z = np.linspace(1, 2, 5)
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [62]:
z[0]

1.0

In [63]:
z[0: 2]

array([1.  , 1.25])

In [64]:
z[-1]

2.0

In [65]:
z = np.array([[1, 2], [3, 4]])
z

array([[1, 2],
       [3, 4]])

In [66]:
z[0, 0]

1

In [67]:
z[0, 1]

2

In [68]:
z[0, :]

array([1, 2])

In [69]:
z[-1]

array([3, 4])

In [70]:
z[:, 1]

array([2, 4])

In [100]:
z = np.linspace(2, 4, 5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [73]:
indices = np.array((0, 2, 3))
z[indices]

array([2. , 3. , 3.5])

In [74]:
z[np.array((0, 2, 3))]

array([2. , 3. , 3.5])

In [75]:
print(z)

[2.  2.5 3.  3.5 4. ]


In [76]:
print(np.array((0, 2, 3)))

[0 2 3]


In [80]:
z[[0, 2, 3]]

array([2. , 3. , 3.5])

In [82]:
d = np.array([0, 1, 1, 0, 0], dtype = bool)
d

array([False,  True,  True, False, False])

In [83]:
z[d]

array([2.5, 3. ])

In [109]:
z = np.empty(2)
z

array([2.5, 3. ])

In [102]:
z[:] = 42
z

array([42., 42., 42.])

In [116]:
a = np.array((4, 8, 2, 1))
a

array([4, 8, 2, 1])

In [117]:
a.sort()
a

array([1, 2, 4, 8])